-- KH계정이 VIEW를 생성할 수 있는 권한 부여
GRANT CREATE VIEW TO KH;

-- KH계정이 동의어를 생성할 수 있는 권한 부여(비공개 동의어)
GRANT CREATE SYNONYM TO KH;
GRANT CREATE 

CREATE USER test00 IDENTIFIED BY 1234;
GRANT CONNECT,RESOURCE TO test00;

--공개 동의어 생성
CREATE PUBLIC SYNONYM DEPT FOR KH.DEPARTMENT;
DROP PUBLIC SYNONYM DEPT;

--test00계정에 KH의 DEPARTMENT테이블 조회 권한 부여
GRANT SELECT ON KH.DEPARTMENT TO test00;
GRANT SELECT ON KH.EMPLOYEE TO test00;

CREATE USER khtest IDENTIFIED BY 1234;
GRANT CONNECT, RESOURCE TO khtest;
GRANT CREATE SYNONYM TO khtest;
GRANT CREATE VIEW TO khtest;


------------------------------------
CREATE USER exam01 IDENTIFIED BY 1234;
GRANT CONNECT,RESOURCE TO exam01;

------------------------------------
CREATE USER DBEXAM IDENTIFIED BY 1234;
GRANT CONNECT,RESOURCE TO DBEXAM;**


