-- DML
-- 회원(이름,나이,주소,성별,아이디,패스워드,가입일)

CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(20),
    MEMBER_PW VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_AGE NUMBER,
    ADDRESS VARCHAR2(500),
    GENDER CHAR(6),
    ENROLL_DATE DATE
);
DROP TABLE MEMBER_TBL;
SELECT * FROM MEMBER_TBL;
-- INSERT : 테이블에 데이터를 삽입하는 구문
-- 1) INSERT INTO 테이블 이름 (컬럼이름1,컬럼이름2,...) VALUES(값1,값2,...);
INSERT INTO MEMBER_TBL(MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,ADDRESS,GENDER,ENROLL_DATE) VALUES('user1','1234','유저1',20,'인천시 부평구 삼산동','남자',SYSDATE);
INSERT INTO MEMBER_TBL(MEMBER_ID,MEMBER_PW,MEMBER_NAME,MEMBER_AGE,ADDRESS,GENDER,ENROLL_DATE) VALUES('user2','1111','유저2',23,'인천시 부평구 구산동','여자',SYSDATE);
INSERT INTO MEMBER_TBL(MEMBER_ID,MEMBER_PW,MEMBER_NAME) VALUES('user3','3333','유저3');
INSERT INTO MEMBER_TBL(MEMBER_NAME,MEMBER_AGE,GENDER) VALUES('user4',25,'남자');

--2) INSERT INTO 테이블명 VALUES (값1,값2....); 값을 순서에 맞춰서 7개 다 적어줘야함.
INSERT INTO MEMBER_TBL VALUES('user5','5555','유저5',25,'인천시 부평구 오산동','남자',SYSDATE);

















