CREATE TABLE MEMO(
    NO      NUMBER          PRIMARY KEY,
    NAME    VARCHAR2(20)    NOT NULL,
    MSG     VARCHAR2(100)   NOT NULL,
    WRITEDAY    DATE
);
INSERT INTO MEMO VALUES(101,'한석규','환영합니다',SYSDATE);
INSERT INTO MEMO VALUES(102,'유관순','건강하세요',SYSDATE);
INSERT INTO MEMO VALUES(103,'이순신','감사합니다',SYSDATE);
SELECT * FROM MEMO;
commit;
DROP TABLE MEMO;