/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.82
 * Generated at: 2022-08-31 06:52:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import kr.or.iei.member.model.vo.Member;

public final class signupFrm_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/views/common/header.jsp", Long.valueOf(1661922563817L));
    _jspx_dependants.put("/WEB-INF/views/common/footer.jsp", Long.valueOf(1661910688471L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("kr.or.iei.member.model.vo.Member");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	.input-wrap{\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("	}\r\n");
      out.write("	.input-wrap > label{\r\n");
      out.write("		font-size : 1.1em;\r\n");
      out.write("		margin-bottom: 10px;\r\n");
      out.write("		display: block;\r\n");
      out.write("	}\r\n");
      out.write("	.submit-btn{\r\n");
      out.write("		padding: 15px;\r\n");
      out.write("		margin: 20px 0px;\r\n");
      out.write("	}\r\n");
      out.write("	.input-wrap>.id-wrap{\r\n");
      out.write("		display: flex;\r\n");
      out.write("	}\r\n");
      out.write("	.input-wrap>.id-wrap>#memberId{\r\n");
      out.write("		width: 80%;\r\n");
      out.write("	}\r\n");
      out.write("	.input-wrap>.id-wrap>#idChkBtn{\r\n");
      out.write("		width: 20%;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    ");

    	Member m = (Member)session.getAttribute("m");
    
      out.write("\r\n");
      out.write("    <!-- 구글 아이콘 -->\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/icon?family=Material+Icons\" rel=\"stylesheet\">\r\n");
      out.write("    <!-- jquery -->\r\n");
      out.write("    <script src=\"/js/jquery-3.6.0.js\"></script>\r\n");
      out.write("    <!-- 기본 CSS -->\r\n");
      out.write("    <link rel=\"stylesheet\" href=\"/css/default.css\" />\r\n");
      out.write("    <!-- 기본 js -->\r\n");
      out.write("    <script src=\"/js/default.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    <header>\r\n");
      out.write("      <div class=\"site-logo\">\r\n");
      out.write("        <a href=\"/\">Jin's WORLD</a>\r\n");
      out.write("      </div>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ul class=\"navi\">\r\n");
      out.write("          <li><a href=\"#\">메뉴-1</a></li>\r\n");
      out.write("          <li><a href=\"#\">메뉴-2</a></li>\r\n");
      out.write("          <li><a href=\"#\">메뉴-3</a></li>\r\n");
      out.write("          <li><a href=\"#\">메뉴-4</a></li>\r\n");
      out.write("          <li>\r\n");
      out.write("			<a href=\"#\">메뉴-5</a>\r\n");
      out.write("            <ul class=\"sub-navi\">\r\n");
      out.write("              <li><a href=\"#\">sub-1</a></li>\r\n");
      out.write("              <li><a href=\"#\">sub-2</a></li>\r\n");
      out.write("              <li><a href=\"#\">sub-3</a></li>\r\n");
      out.write("            </ul>\r\n");
      out.write("           </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("      </nav>\r\n");
      out.write("      <div class=\"header-link\">\r\n");
      out.write("      	");
if(m == null){
      out.write("\r\n");
      out.write("        <button class=\"btn bc11 modal-open-btn\" target=\"#login-modal\">SIGN IN</button>\r\n");
      out.write("        <a class=\"btn bc11\" href=\"/signUpFrm.do\">SIGN UP</a>\r\n");
      out.write("        ");
}else{ 
      out.write("\r\n");
      out.write("        <a class=\"btn bc11\">");
      out.print(m.getMemberName() );
      out.write("</a>\r\n");
      out.write("        <a class=\"btn bc11\" href=\"/logOut.do\">LOGOUT</a>\r\n");
      out.write("        ");
} 
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("    </header>\r\n");
      out.write("    ");
if(m==null){ 
      out.write("\r\n");
      out.write("    <div id=\"login-modal\" class=\"modal-bg\">\r\n");
      out.write("      <div class=\"modal-wrap\">\r\n");
      out.write("        <div class=\"modal-head\">\r\n");
      out.write("          <h2>SIGN IN</h2>\r\n");
      out.write("          <span class=\"material-icons close-icon modal-close\">close</span>\r\n");
      out.write("        </div>\r\n");
      out.write("        <form action=\"/signIn.do\" method=\"post\">\r\n");
      out.write("	        <div class=\"modal-content\">\r\n");
      out.write("	          <div class=\"input-box\">\r\n");
      out.write("	          	<label for=\"signId\">아이디</label>\r\n");
      out.write("	          	<input type=\"text\" name=\"signId\" class=\"input-form\" placeholder=\"아이디 입력\">\r\n");
      out.write("	          </div>\r\n");
      out.write("	          <div class=\"input-box\">\r\n");
      out.write("	          	<label for=\"signPw\">비밀번호</label>\r\n");
      out.write("	          	<input type=\"password\" name=\"signPw\" class=\"input-form\" placeholder=\"비밀번호 입력\">	          \r\n");
      out.write("	          </div>\r\n");
      out.write("	          <div class=\"input-box link-box\">\r\n");
      out.write("	          	<a href=\"#\">아이디/비밀번호 찾기</a>\r\n");
      out.write("	          </div>\r\n");
      out.write("	        </div>\r\n");
      out.write("	        <div class=\"modal-foot\">\r\n");
      out.write("	          <button type=\"submit\" class=\"btn bc11\">로그인</button>\r\n");
      out.write("	          <button type=\"button\" class=\"btn bc1 modal-close\">취소</button>\r\n");
      out.write("	        </div>\r\n");
      out.write("        </form>\r\n");
      out.write("	  </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    ");
} 
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    ");
      out.write("\r\n");
      out.write("	<div class=\"page-content\">\r\n");
      out.write("		<div class=\"page-title\">회원가입</div>\r\n");
      out.write("		<form name=\"checkIdFrm\" action=\"/checkId.do\">\r\n");
      out.write("			<input type=\"hidden\" name=\"checkId\">\r\n");
      out.write("		</form>\r\n");
      out.write("		<form action=\"/signUp.do\" method=\"post\">\r\n");
      out.write("			<div class=\"input-wrap\">\r\n");
      out.write("				<label for=\"memberId\">아이디</label>\r\n");
      out.write("				<div class=\"id-wrap\">\r\n");
      out.write("					<input type=\"text\" name=\"memberId\" id=\"memberId\" class=\"input-form\">\r\n");
      out.write("					<button type=\"button\" id=\"idChkBtn\" class=\"btn bc2\">중복체크</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-wrap\">\r\n");
      out.write("				<label for=\"memberPw\">비밀번호</label>\r\n");
      out.write("				<input type=\"password\" name=\"memberPw\" id=\"memberPw\" class=\"input-form\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-wrap\">\r\n");
      out.write("				<label for=\"memberName\">이름</label>\r\n");
      out.write("				<input type=\"text\" name=\"memberName\" id=\"memberName\" class=\"input-form\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-wrap\">\r\n");
      out.write("				<label for=\"memberPhone\">전화번호</label>\r\n");
      out.write("				<input type=\"text\" name=\"memberPhone\" id=\"memberPhone\" class=\"input-form\" placeholder=\"010-0000-0000\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"input-wrap\">\r\n");
      out.write("				<label for=\"memberAddr\">주소</label>\r\n");
      out.write("				<input type=\"text\" name=\"memberAddr\" id=\"memberAddr\" class=\"input-form\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"submit-btn\">\r\n");
      out.write("				<button type=\"submit\" class=\"btn bc66 bs4\">회원가입</button>\r\n");
      out.write("			</div>\r\n");
      out.write("		</form>\r\n");
      out.write("	</div>\r\n");
      out.write("	<script>\r\n");
      out.write("		$(\"#idChkBtn\").on(\"click\",function(){\r\n");
      out.write("			const memberId = $(this).prev().val();\r\n");
      out.write("			if(memberId == \"\"){\r\n");
      out.write("				alert(\"아이디를 입력하세요\");\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			$(\"[name=checkId]\").val(memberId);\r\n");
      out.write("			const popup = window.open(\"\",\"checkId\",\"left=900px, top=500px, width=300px, height=200px, menubar=no, status=no, scrollbars=yes\");\r\n");
      out.write("			//새 창에서 form을 전송하기 위한 연결작업(저 이름 Frm이라는 폼태그를 checkId에서 처리를 하겠다)\r\n");
      out.write("			$(\"[name=checkIdFrm]\").attr(\"target\",\"checkId\");\r\n");
      out.write("			$(\"[name=checkIdFrm]\").submit();\r\n");
      out.write("		});\r\n");
      out.write("	</script>\r\n");
      out.write("	");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    <footer>\r\n");
      out.write("      <div class=\"footer-content\">\r\n");
      out.write("        <ul>\r\n");
      out.write("          <li><a href=\"#\">이용약관</a></li>\r\n");
      out.write("          <li><a href=\"#\">개인정보취급방침</a></li>\r\n");
      out.write("          <li><a href=\"#\">인재채용</a></li>\r\n");
      out.write("          <li><a href=\"#\">제휴문의</a></li>\r\n");
      out.write("          <li><a href=\"#\">인스타그램</a></li>\r\n");
      out.write("        </ul>\r\n");
      out.write("        <p>Made by LeeYunSu</p>\r\n");
      out.write("        <p>\r\n");
      out.write("          KH정보교육원 당산지원 A강의장 수업자료입니다. 무단복제를 허용하지\r\n");
      out.write("          않습니다.\r\n");
      out.write("        </p>\r\n");
      out.write("      </div>\r\n");
      out.write("    </footer>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
